{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "test_id",
    "query": "SELECT DISTINCT sensor_id FROM dynamic_table_temperature\nORDER BY sensor_id"
   },
   {
    "name": "data_type",
    "query": "SELECT DISTINCT `type` FROM (\n    SELECT `type` FROM dynamic_table_humidity\n    UNION ALL\n    SELECT `type` FROM dynamic_table_temperature\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Test map",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sensor_id as metric,\r\n  latitude as lat,\r\n  longitude as lon,\r\n  temperature as value,\r\n  toDateTime(timestamp) as time\r\nFROM dynamic_table_temperature\r\nWHERE\r\n  (sensor_id, timestamp) IN (\r\n    SELECT\r\n      sensor_id,\r\n      max(timestamp) as max_timestamp\r\n    FROM dynamic_table_temperature\r\n    GROUP BY sensor_id\r\n  )\r\n  AND '$data_type' = \"type\"\r\nORDER BY time\r\nUNION ALL\r\nSELECT\r\n  sensor_id as metric,\r\n  latitude as lat,\r\n  longitude as lon,\r\n  humidity as value,\r\n  toDateTime(timestamp) as time\r\nFROM dynamic_table_humidity\r\nWHERE\r\n  (sensor_id, timestamp) IN (\r\n    SELECT\r\n      sensor_id,\r\n      max(timestamp) as max_timestamp\r\n    FROM dynamic_table_humidity\r\n    GROUP BY sensor_id\r\n  )\r\n  AND '$data_type' = \"type\"\r\nORDER BY time",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sensor_id as metric,\r\n  latitude as lat,\r\n  longitude as lon,\r\n  temperature as value,\r\n  toDateTime(timestamp) as time\r\nFROM dynamic_table_temperature\r\nWHERE\r\n  (sensor_id, timestamp) IN (\r\n    SELECT\r\n      sensor_id,\r\n      max(timestamp) as max_timestamp\r\n    FROM dynamic_table_temperature\r\n    GROUP BY sensor_id\r\n  )\r\n  AND 'Temperature Sensor' = '$data_type'\r\nORDER BY time;",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\r\n  sensor_id as metric,\r\n  latitude as lat,\r\n  longitude as lon,\r\n  humidity as value,\r\n  toDateTime(timestamp) as time\r\nFROM dynamic_table_humidity\r\nORDER BY time DESC\r\nLIMIT 10;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Temperature map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sensor_id as metric,\r\n  latitude as lat,\r\n  longitude as lon,\r\n  temperature as value,\r\n  toDateTime(timestamp) as time\r\nFROM dynamic_table_temperature\r\nWHERE\r\n  (sensor_id, timestamp) IN (\r\n    SELECT\r\n      sensor_id,\r\n      max(timestamp) as max_timestamp\r\n    FROM dynamic_table_temperature\r\n    GROUP BY sensor_id\r\n  )\r\nORDER BY time",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Temperature Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    timestamp AS time,\r\n    sensor_id,\r\n    temperature AS value\r\nFROM dynamic_table_temperature\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time, sensor_id",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Humidity Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sensor_id as metric,\r\n  latitude as lat,\r\n  longitude as lon,\r\n  humidity as value,\r\n  toDateTime(timestamp) as time\r\nFROM dynamic_table_humidity\r\nWHERE\r\n  (sensor_id, timestamp) IN (\r\n    SELECT\r\n      sensor_id,\r\n      max(timestamp) as max_timestamp\r\n    FROM dynamic_table_humidity\r\n    GROUP BY sensor_id\r\n  )\r\nORDER BY time",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Humidity Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    timestamp AS time,\r\n    sensor_id,\r\n    humidity AS value\r\nFROM dynamic_table_humidity\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time, sensor_id",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Charging State Map",
   "type": "geomap",
   "description": "Stato (attivo o spento) delle colonnine per caricare le auto",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sensor_id,\r\n  type,\r\n  state,\r\n  latitude,\r\n  longitude,\r\n  timestamp\r\nFROM\r\n  dynamic_table_charging\r\nWHERE\r\n  (sensor_id, timestamp) IN (\r\n    SELECT\r\n      sensor_id,\r\n      MAX(timestamp) as max_timestamp\r\n    FROM\r\n      dynamic_table_charging\r\n    GROUP BY\r\n      sensor_id\r\n  )",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Test Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"sensor_id\" as metric,\r\n  \"temperature\",\r\n  toDateTime(\"timestamp\") as time\r\nFROM \"dynamic_table_temperature\"\r\nWHERE\r\n  \"sensor_id\" = '$test_id'\r\nORDER BY \"timestamp\" ASC",
     "selectedFormat": 4
    }
   ]
  }
 ]
}