#docker-compose.yaml

version: '3.6'
services:
  zookeeper:
    image: zookeeper
    container_name: city_zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped


  kafka:
    image: bitnami/kafka
    container_name: city_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=city_topic:1:1
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_LOG_RETENTION_BYTES=4073741824
      - KAFKA_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_RETENTION_CHECK_INTERVAL_MS=300000
    restart: unless-stopped


  clickhouse:
    image: bitnami/clickhouse
    container_name: city_clickhouse
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


  grafana:
    image: grafana/grafana
    container_name: city_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource, volkovlabs-variable-panel
    depends_on:
      - clickhouse
    volumes:
      #- grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards


  data_producer:
    image: python:3.8
    container_name: city_data_producer
    volumes:
      - ./producer:/app/producer
    depends_on:
      - kafka
    command: ["sh", "-c", "pip install kafka-python==2.0.2 && python /app/producer/producer.py"]


  data_consumer:
    image: python:3.8
    container_name: city_data_consumer
    volumes:
      - ./consumer.py:/app/consumer.py
    depends_on:
      - kafka
      - clickhouse
    command: ["sh", "-c", "pip install kafka-python==2.0.2 clickhouse-driver==0.2.0 && python /app/consumer.py"]

volumes:
  grafana-storage: {}
  provisioning: {}
  
